spring.application.name=mall



mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mybatis/map/*_mapper.xml
server.servlet.jsp.init-parameters.development=true

spring.data.redis.host=localhost
spring.data.redis.port=6379