spring.application.name=mall

##mysql


spring.datasource.url=jdbc:mysql://localhost:3306/hrms
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mybatis/map/*_mapper.xml
server.servlet.jsp.init-parameters.development=true

spring.data.redis.host=localhost
spring.data.redis.port=6379