openai:
  api-key: ${OPENAI_API_KEY}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wjkim0331@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://gallant_cannon:3306/hrms
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, beans, httptrace, info, metrics, prometheus



